package com.bawei.week2_1.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.week2_1.model.bean.LeftBean;
import com.bawei.week2_1.model.bean.RightBean;

import com.bawei.week2_1.database.LeftBeanDao;
import com.bawei.week2_1.database.RightBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig leftBeanDaoConfig;
    private final DaoConfig rightBeanDaoConfig;

    private final LeftBeanDao leftBeanDao;
    private final RightBeanDao rightBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        leftBeanDaoConfig = daoConfigMap.get(LeftBeanDao.class).clone();
        leftBeanDaoConfig.initIdentityScope(type);

        rightBeanDaoConfig = daoConfigMap.get(RightBeanDao.class).clone();
        rightBeanDaoConfig.initIdentityScope(type);

        leftBeanDao = new LeftBeanDao(leftBeanDaoConfig, this);
        rightBeanDao = new RightBeanDao(rightBeanDaoConfig, this);

        registerDao(LeftBean.class, leftBeanDao);
        registerDao(RightBean.class, rightBeanDao);
    }
    
    public void clear() {
        leftBeanDaoConfig.clearIdentityScope();
        rightBeanDaoConfig.clearIdentityScope();
    }

    public LeftBeanDao getLeftBeanDao() {
        return leftBeanDao;
    }

    public RightBeanDao getRightBeanDao() {
        return rightBeanDao;
    }

}
