package com.bawei.week2_1.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.week2_1.model.bean.RightBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RIGHT_BEAN".
*/
public class RightBeanDao extends AbstractDao<RightBean, Void> {

    public static final String TABLENAME = "RIGHT_BEAN";

    /**
     * Properties of entity RightBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Rightjson = new Property(0, String.class, "rightjson", false, "RIGHTJSON");
    }


    public RightBeanDao(DaoConfig config) {
        super(config);
    }
    
    public RightBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RIGHT_BEAN\" (" + //
                "\"RIGHTJSON\" TEXT);"); // 0: rightjson
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RIGHT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RightBean entity) {
        stmt.clearBindings();
 
        String rightjson = entity.getRightjson();
        if (rightjson != null) {
            stmt.bindString(1, rightjson);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RightBean entity) {
        stmt.clearBindings();
 
        String rightjson = entity.getRightjson();
        if (rightjson != null) {
            stmt.bindString(1, rightjson);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public RightBean readEntity(Cursor cursor, int offset) {
        RightBean entity = new RightBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // rightjson
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RightBean entity, int offset) {
        entity.setRightjson(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(RightBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(RightBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(RightBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
